server:
  servlet:
    session:
      tracking-modes: cookie
  port: 9010

spring:
  datasource:
    url: jdbc:oracle:thin:211.38.173.250:1521:xe
    username: akiya
    password: 1234
    driver-class-name: oracle.jdbc.driver.OracleDriver 
  messages:
    basename: i18n/messages/message, i18n/exceptions/exception
    encoding: UTF-8
    cache-duration: 30
    always-use-message-format: true
    use-code-as-default-message: true
    fallback-to-system-locale: true
    
mybatis:
#  type-aliases-package: com.example.board.model
  mapper-locations: classpath:mapper/**/*.xml
  config-location: classpath:config/mybatis-config.xml
